name: Nightly cron job
on:
    push:
        branches:
            - master

    schedule:
        - cron: '0 0 * * 1-5'

jobs:
    Check_and_Send_Email:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Master Branch
              uses: actions/checkout@v1

            - name: Setup node 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install Dependencies
              run: npm install

            - name: Check Price and Send Email
              run: node index.js ${{ secrets.USERNAME }} ${{ secrets.PASS }} ${{ secrets.EMAILS }}
